### ISSUE TITLE
No changeset description anymore

### ISSUE THREAD

**Issue by kvlahromei** [tyrasd/latest-changes#4]
Hi, I noticed, that the listing now lacks the description text of all changesets: 
![no changeset descr](https://user-images.githubusercontent.com/8177370/31650313-145d931a-b317-11e7-9307-80979b52a286.png)

This is sad, as the text allows an fast understanding of what happened at the edit 👍 
I can confirm this bug on FF, IE and chrome.

**Comment by tyrasd** [comment]
strange, this works just fine for me (tried on chromium and firefox):

![selection_046](https://user-images.githubusercontent.com/1927298/31653113-ad042656-b321-11e7-8833-8a0801258beb.png)

**Comment by tyrasd** [comment]
ooh, I think I see the issue now. OSM's [`changesets`](https://wiki.openstreetmap.org/wiki/API_v0.6#Query:_GET_.2Fapi.2F0.6.2Fchangesets) api call (which is used to fetch the changeset descriptions) only returns at most 100 entries. That causes the page to crash [here](https://github.com/tyrasd/latest-changes/blob/gh-pages/js/site.js#L172) when there are more than 100 changesets to be displayed. Should be easy to fix.

**Comment by kvlahromei** [comment]
@tyrasd  Thanks for fixing!
