### ISSUE TITLE
Color change

### ISSUE THREAD

**Issue by wambacher** [tyrasd/latest-changes#9]
Hi,

Could you please darken the light green on the changes, please? Especially the texts on the left side.

These light green texts are - at least for me - hard to read, because the contrast to the white background is very low.

**Comment by rene78** [comment]
Hi @wambacher 

I changed the color in my fork of this repository. Furthermore the width of the map has been increased.

I guess @tyrasd is busy with other things at the moment. Maybe you can try out my slightly updated version instead: https://github.com/rene78/latest-changes

Cheers
René

**Comment by tyrasd** [comment]
fixed in #8, thanks @rene78
